### ISSUE TITLE
Window cover that doesn't work well

### ISSUE THREAD

**Issue by iDreamsX** [milo526/homebridge-tuya-web#171] opened 2021-01-14 20:20 UTC
Hello, 
I use your plugin for shutters from SmartLife. 
It works fine, except that I have to reload the Homekit app twice to get the right status of the different devices.
Wanting the "STOP" option, I took your version 8.0.0, but I don't have it even with the option activated. I don't know if this is a bug. But hey.
I thought you would have used the options available there for alarms with 3/4 predefined options: "Open", "Pause", "(half)", "Close".
![a2d7c65cfde556af3eae227afa57ef154d8d7663](https://user-images.githubusercontent.com/37273978/104644511-229dd780-56ae-11eb-8d6d-42584259dd20.jpeg)

I turned to a fix proposed by bSr43 ( https://github.com/bsr43/homebridge-tuya-web ) for the status of the shutters, and it works really well, I don't know if you can implement it in a future version, because the status and the function is really correct. The information "Opening" does not stay indefinitely like at home, I don't know if it tries to communicate with the server, but it has some trouble. I have to reload the app to get the correct status.

Thank you in advance and congratulations for your plugin, I can finally leave quietly from my home with automations for Homekit !

**Comment by Aekung** [comment] 2021-01-15 15:10
The window covers are not working very well for me as well. 1 cover is partially working, other 2 are just not working at all. However, by installing a fix from bSr43 does really solve all the problem and made all 3 covers work as it should be. 

@milo526 Please kindly take a look on what changed in the fix from bSr43 as it does really solve the window covers problem. Now the only thing that is still not working is the percentage opening and closing but the rest are working really well.

Anyway, thank you very much for this awesome plugin!

**Comment by milo526** [comment] 2021-01-15 15:19
Duplicate of #143

**Closed by milo526** 2021-01-15 15:19 UTC
Labels: enhancement

**Comment by rulez86** [comment] 2021-01-16 20:32
> The window covers are not working very well for me as well. 1 cover is partially working, other 2 are just not working at all. However, by installing a fix from bSr43 does really solve all the problem and made all 3 covers work as it should be.
> 
> @milo526 Please kindly take a look on what changed in the fix from bSr43 as it does really solve the window covers problem. Now the only thing that is still not working is the percentage opening and closing but the rest are working really well.
> 
> Anyway, thank you very much for this awesome plugin!

Hello,
can you quickly explain how you did install the fix? Not working for me, Homebridge always installs version 0.7.1 and not actual master.
