### ISSUE TITLE
Characteristic warning: Brightness was supplied illegal value

### ISSUE THREAD

**Issue by Bjarlex** [milo526/homebridge-tuya-web#374] opened 2021-12-15 14:53 UTC
**Describe the bug**

I am getting this characteristic warning every 5 minutes or so:

[15/12/2021, 15:24:56] [TuyaWebPlatform] [Star Projector] Characteristic.Brightness - Characteristic 'Brightness' will receive value higher than allowed (281.1111111111111) since provided Tuya value (263) exceeds configured maximum Tuya value (100). Please update your configuration!
[15/12/2021, 15:24:56] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 281.1111111111111 exceeded maximum of 100. See https://git.io/JtMGR for more info.

**Steps To Reproduce**

1. Start Homebridge
2. look at logs

**Plugin Version**
  
v1.1.0

 **Homebridge Config**
 
 
 ```json
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xx@email.com",
                "password": "xxxx",
                "countryCode": "45",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": true,
            "platform": "TuyaWebPlatform"
        }
```
 
 **Device Config**
 
 -

 **Additional Context**
 
I had no warnings before the new update, I have looked at the similar issues and this seems to be mentioned several places including issues  #370, #149 , #370 which have been closed with no apparent solution

Updating to the pre-release 1.1.0-1 also does not solve the issue for me

@milo526 thanks for the otherwise great plugin, this is the only issue i've ever had!

**Comment by milo526** [comment] 2021-12-15 14:55
You link 2 issues, one of which is open and the other of which is closed stating that it is a duplicate of #149.
I'll also close this issue as a duplicate of #149, please add any extra information you have to that issue.

**Closed by milo526** 2021-12-15 14:55 UTC
Labels: bug
