### ISSUE TITLE
[Request] Garage Door Opener

### ISSUE THREAD

**Issue by imtitanic** [milo526/homebridge-tuya-web#104] opened 2020-10-28 05:01 UTC
> Did you check other issues to see if somebody already requested support?

Yup, but the issue (#45) was closed for inactivity

**Device type**

- Garage Door Opener

**Device information**
```
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [{   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1537847617560vAgbw/1566982841d9f5a935d5c.png',
                                      'id': '77010881483fda436772',
                                      'name': 'Garage Door'}],
                   'scenes': []}}
```

**Comment by milo526** [comment] 2020-10-28 07:58
Hello,

Thank you for expressing your interests. (And thank you for immediately including the API data, this is really helpful and often forgotten!)

As you can see in this data it states ```'ha_type': 'switch',``` which means that the API that this plugins uses, believes that your device is a switch. Sadly there is nothing I can do about this, this is a Tuya limitation.


Furthermore; as we can see in [the homebridge documentation](https://developers.homebridge.io/#/service/GarageDoorOpener), the garage door accessory requires quite a lot of characteristics. The API does not supply this information.

Sadly I think I cannot help you with this right now.

**Comment by Sehiro** [comment] 2020-10-28 08:45
Hi,
question is, what happens if you activate the switch in home? Does it activate the garage door? How does interaction with the switch translate to the open/close behaviour of the door? These garage door openers are usually a simple relay which are installed in parallel with the physical button in your garage. The have no way of knowing what is going on with the actual door.

My guess is, that if you activate and deactivate the switch to make the garage door move or to stop the door. Like a pushbutton. A proper security device in homekit could be emulated BUT there is no way for home to know the actual state of the door (if it is opened, closed or anywhere in between).

So if you open the door in home, a switch flick on and off could be sent to your opener via tuya and your door would move. In home we could display the door as open then. Closing the door in home could again send an on and off flick to the device and the door would move again. Then the door would show as closed in homekit. The problem is, that the actual state of the garage door does not need to represent the displayed state in home and there is no way for home to find out what the actual state is. In other words: if you use the manual button in your garage to open the door, homekit still shows it as closed and if you use home to open the door, it would physically close the door. States would be reversed.)

I personally could live with this behaviour. 

If there was a way to get the state of the door (open/closed) by an extra device like a window contact installed on the door. The state in home could be displayed correctly. Then there would be minimum guesswork involved.

cheers

Stefan

**Comment by imtitanic** [comment] 2020-10-28 09:05
Hi again!

> If you have some other ideas or want to discuss this further please feel free (within 10 days, otherwise this issue will be automatically closed due to inactivity 😛)

Looking the homebridge doc, can use the state of the switch to get the current/target state? The Obstruction Detected can be faked? Do you think there is a way that the "switch" shows the on / off according to the state of the garage door and use it?

The 'state' in data changes (false/true) considering that the state changes if it is open or closed.

> question is, what happens if you activate the switch in home? Does it activate the garage door? How does interaction with the switch translate to the open/close behaviour of the door? These garage door openers are usually a simple relay which are installed in parallel with the physical button in your garage. 

Hi, @Sehiro, yes, it's a simple relay (can I listening in person) but actually this happens:

If I press the "switch" while it is off, it sends the signal to the motor to open the door but it stays on until I press it again (and it sends signal again to the motor). but in case of opening it with the wall / remote control, the status changes in the Tuya app but not in Home.

>The have no way of knowing what is going on with the actual door.

In fact yes :D! As I mentioned above, the state of the switch changes according to the actual state of the door using a sensor.

**Comment by milo526** [comment] 2020-12-20 21:49
Shiny new pre-release v0.6.1 brings this feature.

You will need to overwrite the device type to "garage" and it should then work.

To install v0.6.1 you will need to [install an "alternate version"](https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions) as it is not yet publicly released.

**Closed by milo526** 2020-12-20 21:49 UTC
Labels: active, new device

**Comment by taaa22** [comment] 2020-12-21 06:10
It looks like we are having a lot of Christmas gifts this year 😍.
Tested and works perfectly.

**Comment by smarthomekid** [comment] 2021-08-17 18:15
quesiton to the garage opener. Did the state of the door make it in the standard installation? how does it need to be configured?

**Comment by milo526** [comment] 2021-08-19 07:09
@smarthomekid please see the section on [overruling device types](https://github.com/milo526/homebridge-tuya-web#overruling-device-types) and set the device type to `garage`

**Comment by CSHAW77** [comment] 2024-04-26 17:48
Hello,

I have overruled the device type to garage and see 3 switches on homekit, one is open, one is close, not sure what the third one is.  It does show in homekit, but does not activate the garage door. The open & close are acting as rely staying one for a second and then turning back off the third unknown button stays on/off as a switch. Below is the garage door model I have:
https://a.co/d/a8YlhH4
