### ISSUE TITLE
Been getting this message last couple months, and when trying to use siri, it is slow and sometimes does not do request.

### ISSUE THREAD

**Issue by vhm14u2c** [milo526/homebridge-tuya-web#229] opened 2021-03-09 11:47 UTC
![image](https://user-images.githubusercontent.com/73516993/110461871-00b54580-809e-11eb-8ab2-c2c330c2ab03.jpeg)

**Describe the bug**

when trying to use siri, it is slow and sometimes does not do request.

Prior to a couple months ago, was working pretty well 

**Steps To Reproduce**

**Plugin Version**
 
 1.3.2
 **Homebridge Config**
 
 {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "redacted ",
                "password": "redacted ",
                "countryCode": "1",
                "platform": "tuya"
            },
            "scenes": false,
            "platform": "TuyaWebPlatform"
        },

 ```json

```
 
 **Device Config**
 
 Not ready to do this yet, but it's worked fine in the past, prior to two months ago, seemed flawless 
![image](https://user-images.githubusercontent.com/73516993/110466117-4f191300-80a3-11eb-87f6-37714a198f1f.jpeg)
 **Additional Context**

**Comment by milo526** [comment] 2021-03-09 11:49
Duplicate of #158

**Closed by milo526** 2021-03-09 11:49 UTC
Labels: bug
