### ISSUE TITLE
Your configuration.json is requesting platform “TuyaWebPlatform” which has not been published by any installed plugin.

### ISSUE THREAD

**Issue by johnhmccauley** [milo526/homebridge-tuya-web#59] opened 2020-08-15 07:55 UTC
After installing the first update in August I get the following error on startup.

Your configuration.json is requesting platform “TuyaWebPlatform” which has not been published by any installed plugin.

I am using HOOBS 

This might help.
https://www.reddit.com/r/HOOBS/comments/hldk8w/myq2_the_requested_platform_myq_was_not/

**Describe the bug**

**Comment by milo526** [comment] 2020-08-15 07:59
Duplicate of #49

**Closed by milo526** 2020-08-15 07:59 UTC
Labels: bug
