### ISSUE TITLE
Homekit shows blind closed when open

### ISSUE THREAD

**Issue by Movieaholic** [milo526/homebridge-tuya-web#315] opened 2021-08-17 10:47 UTC
Im having problems with a zemismart blind motor setup through tuya smart app often showing in homekit as closed when its open every now and then it will show correctly as open then closed again next time it refreshes.

**Comment by davic80** [comment] 2021-08-17 23:03
Same issue with a windows cover from tuya smart life platform here. I’m using the plug-in from docker homebridge with default refresh and configuration with expose stop but it doesn’t. If further information or testing is needed I can do it!

**Comment by Movieaholic** [comment] 2021-08-18 10:58
I tried homebridge-tuya-platform but it has similar issues if blind is open homekit stays in the opening state but never actually reaches the full open state

**Comment by milo526** [comment] 2021-08-19 07:07
Duplicate of #143 (Blinds and curtains are one and the same device with a different name)

**Closed by milo526** 2021-08-19 07:07 UTC
Labels: bug
