### ISSUE TITLE
Open / Closed the wrong way

### ISSUE THREAD

**Issue by RW188** [milo526/homebridge-tuya-web#160] opened 2021-01-04 22:36 UTC
I have successfully managed to get the account added.  (Please add a note into the UI to flag the importance of the account needing to have been created from an email, not Apple etc sign in.  I fell short of this!)

The blind has added, but is reporting open when closed, and closed when open.  I think this has something to do with me having Venetian blinds, so the mid-point is actually open.

**Describe the bug**

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment] 2021-01-05 09:22
> I have successfully managed to get the account added.

🎉 

> (Please add a note into the UI to flag the importance of the account needing to have been created from an email, not Apple etc sign in. I fell short of this!)

Feel free to submit a PR with the proposed changes

> The blind has added, but is reporting open when closed, and closed when open.

Sound an awful lot like this is a duplicate of #143 

>  I think this has something to do with me having Venetian blinds, so the mid-point is actually open.

Could be, might have found something relevant in the rest of the issue template

> **Describe the bug**
> 
> **Steps To Reproduce**
> 
> **Plugin Version**
> 
> **Homebridge Config**
> ```json
> ```
> 
> **Device Config**
> 
> **Additional Context**

Issue template is not filled in.

Closing since this is a duplicate of #143 and the issue template is not filled in.

**Closed by milo526** 2021-01-05 09:22 UTC
Labels: bug

**Comment by RW188** [comment] 2021-01-05 10:34
I have been in touch with Tuya, as I think it might be something to do with how they export the results.  The blinds are actually vertical.
I didn't see the template as completed the report on my phone last night, so will come back once I have something more tangible from Tuya.

Currently:

Left Swing 100 % = Open, but in Tuya this is showing as a roller blind, not vertical.
Right Swing 100% = Closed, as indicated if it was a roller blind.
50% is therefore open, in the case of a vertical blind.

I suspect Tuya need to support other blind types, so the open closed values are transposed into the output to reflect the blind position for other things than just roller.  I can't seem to find anywhere in the Tuya app how to change the blind type.
