### ISSUE TITLE
Fan %

### ISSUE THREAD

**Issue by hamodcraft22** [milo526/homebridge-tuya-web#16] opened 2020-06-19 08:42 UTC
ok so finally a tuya plugin that fully works!!! 

one small problem, the homebridge integration works amazingly but one issue....
when using the device physically "fan" it shows up in hombridge+homekit as ON at 100%, i can change the speed via homekit and it works amazing but I don't know why using the physical switch messes the things up 

also it takes a lot of time to update the statues in homebridge and the "pollingInterval": set to 1 does nothing of a difference

I recommend implementing the same idea of the homebridge-ewelink-max where it refreshes the statues when the homekit app is accessed

**Comment by milo526** [comment] 2020-06-19 08:51
Duplicate of #17

**Closed by milo526** 2020-06-19 08:51 UTC
