### ISSUE TITLE
No stop feature on curtain 

### ISSUE THREAD

**Issue by talrhv** [milo526/homebridge-tuya-web#331] opened 2021-09-26 19:59 UTC
**Describe the bug**

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**
 

hi,

I have the wifi curtain switch and I don’t have a stop button. I can only open or close. I did checked the box that says “stop” on the features but it doesn’t do anything.
I’m using the latest version of the plug-in and also homebridge.

Thanks 
![8905B10D-75A2-4CDE-A498-C7743F20542F](https://user-images.githubusercontent.com/34038314/134822409-9a81f913-d5d5-4835-9a72-12b3e771e062.png)

**Comment by milo526** [comment] 2021-10-02 11:21
Duplicate of #145

**Closed by milo526** 2021-10-02 11:21 UTC
Labels: bug
