### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by gabevf** [milo526/homebridge-tuya-web#102] opened 2020-10-24 19:46 UTC
Hi Milo526,

I've been getting the following error in my logs:

"Authentication error: Get accesstoken failed. Username or password error!"

I've tried using the iot.tuya.com login, as well as the SmartLife app login, and get the same error.

I'm using the (optional?) SmartLife platform in the plugin settings.
Other than that, just attempting different usernames & passwords.
I've also tried resetting the password, to no avail.

I'm using plugin v0.4.8

 
 
Homebridge config v4.28.1

 
 
 ```json

        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xyz@xyz.com",
                "password": "password123",
                "countryCode": "1",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }

```
 

 
 
 Thank you for your efforts in this project, really appreciate your help!
Best,

_
G

**Comment by Nick-Lucas** [comment] 2020-10-25 11:01
@gabevf I've just been tackling the same issue and it really was my own fault. Try resetting your password in the TuyaSmart mobile app and signing in again there, then make sure you use that password in the configuration for this. After restarting Homebridge it should work immediately.

**Comment by gabevf** [comment] 2020-10-27 14:24
Thanks Nick, I appreciate you looking into this. I’ll give it a shot!
Best,

_
G

**Comment by ansred** [comment] 2020-11-02 10:18
+1 Same here getting over and over the same error.

I even tried to reset my password and added extra space in the country code as I live in Canada " 1" 

Same issue

`11/2/2020, 5:14:55 AM] [TuyaWebPlatform] Authentication error: Get accesstoken failed. Username or password error!
2020-11-02T10:14:56.074Z hapNodeJSClient HAP Device discovered Homebridge 5FB5 EC7F
2020-11-02T10:14:56.075Z hapNodeJSClient HAP Device address Homebridge 5FB5 EC7F ->  {
  host: '127.0.0.1',
  port: 51892,
  url: 'http://127.0.0.1:51892',
  deviceID: '0E:C9:C4:EB:5F:B5',
  txt: {
    'c#': '3',
    ff: '0',
    id: '0E:C9:C4:EB:5F:B5',
    md: 'homebridge',
    pv: '1.1',
    's#': '1',
    sf: '0',
    ci: '2',
    sh: 'fdtTZQ=='
  }`


Any luck on your end @gabevf after you did the password reset?

**Comment by ansred** [comment] 2020-11-03 15:56
Found the issue - @gabevf 

The bug that the API doesn't like the dots in the email in username


I also have an account on gmail. Usually when I use it it contains dots before @ i.e. xxx.yyy.zzz@gmail.com. You can create an account like that in the Tuya/Smart Life app but in the Home Assistant integration login with such email fails.

As gmail will deliver e-mails with or without dots to the same account I've created new account on Tuya app without dots like xxxyyyzzz@gmail.com. And I was able to successfully authenticate in Home Assistant Tuya integration.

Thanks! The issue is correctly with "dots" in email. Removing it works fine.

**Comment by milo526** [comment] 2020-11-12 16:12
I'm closing this since the issue seems to be solved. 
I'll make sure the readme contains some information information on keeping dots out of your email adres if possible 😉

**Closed by milo526** 2020-11-12 16:12 UTC
Labels: bug

**Comment by slntopp** [comment] 2020-12-14 11:32
Please, mention this in README😅

**Comment by milo526** [comment] 2020-12-14 11:33
> Please, mention this in README😅

Please make a PR 😃
