### ISSUE TITLE
Receiving this issue in status:

### ISSUE THREAD

**Issue by vivekanandbv** [milo526/homebridge-tuya-web#391] opened 2022-01-05 14:04 UTC
[TuyaWebPlatform] [Solimol] Characteristic.
Brightness - Characteristic ‘Brightness' will receive value higher
than allowed (233.33333333333334) since provided Tuya value (220)
exceeds configured maximum Tuya value (100). Please update your
Configuration!

[@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 233.33333333333334 exceeded maximum of 100. See https://git.io/JtMGR for more info.

[1/5/2022, 2:14:45 PM] [TuyaWebPlatform] [Solimol] Characteristic. ColorTemperature-
Characteristic 'ColorTemperature' will receive value higher than allowed mired (802) since provided Tuya kelvin Value (1247) is lower then configured minimum Tuya kelvin value (71
42.857142857143). Please update your configuration!

My config:

{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "*********",
                "password": "*********",
                "countryCode": "***",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "id": "Solimol",
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }

**Comment by gdotp01** [comment] 2022-01-10 22:44
I’m seeing this as well. I downgraded to 1.0.1 and it has stopped

**Comment by milo526** [comment] 2022-01-16 16:13
This seems to be a duplicate of #388 I'm closing this in favour of that one.

**Closed by milo526** 2022-01-16 16:13 UTC
