### ISSUE TITLE
[TuyaWebPlatform] [GET] Requesting too quickly. - you can query once in 60 seconds

### ISSUE THREAD

**Issue by dacaputo1** [milo526/homebridge-tuya-web#58] opened 2020-08-15 05:37 UTC
**Describe the bug**
Just installed the @milo526/homebridge-tuya-web v0.4.5 plugin. All the Gosund switches show up in Homekit but they show "No Response". These messages get added when I scroll to different rooms in Homekit. If I scroll to a room, and wait a minute, the "No Response" will go away and the switch will work fine. The switch will not work until the "No Response" goes away.
I have:
7 Gosund Smart Switches
4 Gosund Smart Dimmer switches
2 3-way Smart Switches

**To Reproduce**
1. Install @milo526/homebridge-tuya-web v0.4.5 plugin
2. Look in Homebridge Log
3. Scroll to different rooms in Homekit
4. Look in Homebridge Log

**Expected behavior**
Gosund switches show up in Homekit and be able to group them by room

**Screenshots**
![Capture](https://user-images.githubusercontent.com/69698633/90305521-5d92a980-de89-11ea-9359-24cdb053e21e.JPG)

**Device**
 - Plugin: @milo526/homebridge-tuya-web 
 - Version: v0.4.5
 - Model : 8 and 5
 - Device-config: 
Getting credentials
Got credentials
{   'access_token': 'AZhaz1596577035773GJ2N4Y2uEbhrCIq',
    'expires_in': 864000,
    'refresh_token': 'AZhaz1596577035773GJ2N4jeadrFgfLt',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'brightness': '36',
                                                  'online': True,
                                                  'state': 'false'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1547191536z7egzrj0z6e_0.png',
                                      'id': '58200882c82b9656c69b',
                                      'name': 'Bens Room Light'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/15506292077o5z0sbihe_0.png',
                                      'id': '00314174f4cfa23ac568',
                                      'name': 'Living Room Can Lights 2'},
                                  {   'data': {   'brightness': '255',
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1547191536z7egzrj0z6e_0.png',
                                      'id': '34142186c82b9656c778',
                                      'name': 'Office Light'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1519551146071pEnBd/159133868856614057913.png',
                                      'id': '40025745e09806c9434f',
                                      'name': 'Bens Room Fan'},
                                  {   'data': {   'brightness': '255',
                                                  'online': True,
                                                  'state': 'false'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1547191536z7egzrj0z6e_0.png',
                                      'id': '58200882c82b9656e071',
                                      'name': 'Guest Room Light'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1519551146071pEnBd/159133868856614057913.png',
                                      'id': '45142045c82b96c1ec1b',
                                      'name': 'Office Fan'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1519551146071pEnBd/159133868856614057913.png',
                                      'id': '62833736c82b96c5daa1',
                                      'name': 'Living Room Fan Lights'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1519551146071pEnBd/159133868856614057913.png',
                                      'id': '12176102c82b96c5e18e',
                                      'name': 'Living Room Fan'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1519551146071pEnBd/159133868856614057913.png',
                                      'id': '62833736f4cfa20a1a8b',
                                      'name': 'Master Hallway Light'},
                                  {   'data': {   'brightness': '255',
                                                  'online': True,
                                                  'state': 'false'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaus.com/smart/icon/1547191536z7egzrj0z6e_0.png',
                                      'id': '58200882c82b9656c530',
                                      'name': 'Craft Room Light'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/15506292077o5z0sbihe_0.png',
                                      'id': '00314174f4cfa23a968e',
                                      'name': 'Living Room Can Lights'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1519551146071pEnBd/159133868856614057913.png',
                                      'id': '45142045e09806c41e7b',
                                      'name': 'Guest Room Fan'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1519551146071pEnBd/159133868856614057913.png',
                                      'id': '45142045e09806c43d2c',
                                      'name': 'Craft Room Fan'}],
                   'scenes': []}}

**Additional context**
{
    "bridge": {
        "name": "Homebridge F25C",
        "username": "0E:53:C2:C7:F2:5C",
        "port": 51317,
        "pin": "366-35-921"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "************",
                "password": "************",
                "countryCode": "1",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        },
        {
            "email": "*************",
            "name": "myQ",
            "password": "************",
            "platform": "myQ"
        },
        {
            "name": "WeMo",
            "platform": "BelkinWeMo"
        }
    ]
}

**Comment by milo526** [comment] 2020-08-15 07:59
Duplicate of #50

**Closed by milo526** 2020-08-15 07:59 UTC
Labels: bug
