### ISSUE TITLE
Tuya Dehumidifier

### ISSUE THREAD

**Issue by witherel** [milo526/homebridge-tuya-web#119] opened 2020-11-23 18:00 UTC
I know you are working on it. When might climate devices be updated into the plugin?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by milo526** [comment] 2020-11-23 18:01
Duplicate of #63 

Please see my responses there.
No need to open a new issue for this.

**Closed by milo526** 2020-11-23 18:01 UTC
