### ISSUE TITLE
Not getting ststus from Tuya 

### ISSUE THREAD

**Issue by trftrftrf** [milo526/homebridge-tuya-web#301] opened 2021-07-15 16:02 UTC
hi all,

i am not sure if i have missed anything. 

after setup this plugin, i can control all the blind motors from homekit. but homekit does get the status from tyua. 

i saw other users have logs like this:

[7.1.2021, 08:33:04] [TuyaWebPlatform] [Vorhangschalter] - Unsetting debouncedDeviceStateRequestPromise
[7.1.2021, 08:33:04] [TuyaWebPlatform] [Vorhangschalter] - Resolving resolveDeviceStateRequest from cache
[7.1.2021, 08:33:04] [TuyaWebPlatform] [Vorhangschalter] Characteristic.CurrentPosition - [GET] 1
[7.1.2021, 08:33:04] [TuyaWebPlatform] [Vorhangschalter] Characteristic.CurrentPosition - Updating value { online: true, state: 1, target_cover_state: 1 }

but my homebridge log screen does not do or show anything.
if i open the blind from the tuya app, homekit doesn't get the blind status, no matter how long i waited for.

anyone can share some lights?

thanks

**Comment by milo526** [comment] 2021-07-15 18:10
Duplicate of your discussion.

**Closed by milo526** 2021-07-15 18:10 UTC
Labels: bug

**Comment by paqpaqpaq** [comment] 2021-10-01 15:25
I found it seems to be doing this with all accessories. 
switches and dimmers too.
