### ISSUE TITLE
 This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!....

### ISSUE THREAD

**Issue by Tango4us** [milo526/homebridge-tuya-web#389] opened 2022-01-04 15:12 UTC
**Describe the bug**

Following messages appear in the log file:
"This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info."
I moved back to v1.0.2 - it does not report these messages anymore from this older revision.
I also noticed the bridge response is very slow.

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json
{
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "_bridge": {
                "username": "0E:C8:B6:BC:9B:28",
                "port": 33825
            },
            "options": {
                "username": "REDACTED",
                "password": "REDACTED",
                "countryCode": "972",
                "platform": "smart_life",
                "pollingInterval": 1800
            }
```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment] 2022-01-04 15:13
Duplicate of #388

**Closed by milo526** 2022-01-04 15:13 UTC
Labels: bug

**Comment by Paschalis** [comment] 2022-02-05 10:06
BTW what's the minimum polling interval?

Digging a little bit into the code it looks like it doesn't let it go below 10 minutes 
(TUYA_DISCOVERY_TIMEOUT*1e3)

Can't we set it to something like 10 seconds?

**Comment by milo526** [comment] 2022-02-05 14:41
@Paschalis please create a new issue when you have an unrelated question instead of adding them to another issue.
