### ISSUE TITLE
cant change brightness for strip light

### ISSUE THREAD

**Issue by damanveen** [milo526/homebridge-tuya-web#270] opened 2021-05-06 16:39 UTC
Keep getting the following error log whenever I try to change brightness on my strip light. it seems to be getting a value outside its limit

[30/04/2021, 16:47:17] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 294 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[30/04/2021, 16:57:22] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 294 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[06/05/2021, 10:41:04] [TuyaWebPlatform] [Office strip light] Characteristic.Brightness - Tried to set brightness but failed to parse data. 
 {
  color_mode: 'colour',
  online: true,
  state: 'true',
  color: { hue: 125, saturation: 100 }
}

**Comment by milo526** [comment] 2021-05-14 07:43
Duplicate of #149

**Closed by milo526** 2021-05-14 07:43 UTC
