### ISSUE TITLE
No response from accessories in HomeKit but through HOOBS, they work

### ISSUE THREAD

**Issue by aidzer0** [milo526/homebridge-tuya-web#56] opened 2020-08-14 16:16 UTC
**Describe the bug**
Hello, I just updated Tuya to 0.4.3, and now my HOOBS accessories show "No response" on all of my devices. I removed Tuya, the rest of my accessories show correctly and update (DHT thermo sensors). But as soon as I add Tuya back, everything becomes un-responsive through HomeKit, but on HOOBS web UI, I can control the devices/accessories. It's only through HomeKit that everything is unresponsive while tuya is installed.

**Expected behavior**
Responsive devices in HomeKit.

**Screenshots**

**Device**
 - Plugin: @milo526/homebridge-tuya-web
 - Version: 0.4.3
 - Model : 8
 - Device-config: `Getting credentials
Got credentials
{   'access_token': 'AZhaz1570747778502q28hJJQCSdjlXMQ',
    'expires_in': 864000,
    'refresh_token': 'AZhaz1570747778502q28hJ44f5lSFiVw',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/bay1588900714943KlYF/1589188786cafbef5f7af.jpg',
                                      'id': 'ebe633346a5e8e4babsokk',
                                      'name': 'Bedroom Light'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyauGetting credentials
Got credentials{   'access_token': 'AZhaz1570747778502q28hJqPOGu6p8Em',
    'expires_in': 864000,
    'refresh_token': 'AZhaz1570747778502q28hJNh2Squ6aMG',    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},    'payload': {   'devices': [   {   'data': {'online': True, 'sta
te': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyau
s.com/smart/icon/bay1588900714943KlYF/1589188786cafbef5f7af.jpg',
                                      'id': 'ebe633346a5e8e4babsokk
',
                                      'name': 'Bedroom Light'},
                                  {   'data': {'online': True, 'sta
te': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyau
s.com/smart/icon/bay1588900714943KlYF/1589188786cafbef5f7af.jpg',
                                      'id': 'ebbed9aeecba46c038ygvo
',
                                      'name': 'Fan'},
                                  {   'data': {'online': True, 'sta
te': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyau
s.com/smart/icon/bay1588900714943KlYF/1589188786cafbef5f7af.jpg',
                                      'id': 'ebede101956cddbee30kcp',
                                      'name': 'Lounge light'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/bay1588900714943KlYF/1589188786cafbef5f7af.jpg',
                                      'id': 'ebcc8263d537b8c7fc1djg',
                                      'name': 'Fan 2'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'PDO98xqhgg57FCUP',
                                      'name': 'If Schedule:02:30 '
                                              '8/14,\\"Fan\\" Switch 1:OFF'}],
                   'scenes': []}}`

**Additional context**
Only Logs visible: 
[8/14/2020, 09:01:06] [TuyaWebPlatform] Requesting too quickly.
[8/14/2020, 09:01:06] [TuyaWebPlatform] [Fan 2] Characteristic.On - [SET] true 1
[8/14/2020, 09:01:09] [TuyaWebPlatform] [Fan 2] Characteristic.On - [SET] false 0
[8/14/2020, 09:01:09] [TuyaWebPlatform] Requesting too quickly.
[8/14/2020, 09:01:09] [TuyaWebPlatform] [Bedroom Light] Characteristic.On - [GET] Requesting too quickly.
[8/14/2020, 09:01:09] [TuyaWebPlatform] [Fan] Characteristic.On - [GET] Requesting too quickly.
[8/14/2020, 09:01:09] [TuyaWebPlatform] [Lounge light] Characteristic.On - [GET] Requesting too quickly.
[8/14/2020, 09:01:09] [TuyaWebPlatform] [Fan 2] Characteristic.On - [GET] Requesting too quickly.
[8/14/2020, 09:01:09] [TuyaWebPlatform] [Fan 2] Characteristic.On - [GET] Requesting too quickly.
[8/14/2020, 09:01:10] [TuyaWebPlatform] Requesting too quickly.
[8/14/2020, 09:01:11] [TuyaWebPlatform] [Bedroom Light] Characteristic.On - [SET] true 1
[8/14/2020, 09:01:12] [TuyaWebPlatform] [Bedroom Light] Characteristic.On - [SET] false 0
[8/14/2020, 09:01:12] [TuyaWebPlatform] Requesting too quickly.
[8/14/2020, 09:01:13] [TuyaWebPlatform] Requesting too quickly.
[8/14/2020, 09:01:14] [TuyaWebPlatform] Requesting too quickly.

**Comment by milo526** [comment] 2020-08-14 16:17
Duplicate of #50 please see my response there.

Expect a fix shortly

**Closed by milo526** 2020-08-14 16:18 UTC
Labels: bug
