### ISSUE TITLE
Brightness value greater than 100 (Lightbulbs by Geonav)

### ISSUE THREAD

**Issue by lamatuzzi** [milo526/homebridge-tuya-web#228] opened 2021-03-08 23:21 UTC
**Describe the bug**

The plugin is reporting a warning that my lightbulb has a brightness characteristic greater than 100%. I run the script to check if my device can be controlled by the plugin, and the brightness value in the result on Repl.it is 1000 (my lightbulb on smart life app is set to 100%). Can you check this situation? Thanks in advance!
**Steps To Reproduce**

1. I run the Homebridge server and the plugin prints a warning log on my devices

**Plugin Version**
 
 1.0
 **Homebridge Config**
 
 
 ```json
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "amatuzzi01@gmail.com",
                "password": "xxxxxxxx",
                "countryCode": "55",
                "platform": "smart_life",
                "pollingInterval": 1800
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": true,
            "platform": "TuyaWebPlatform"
        }
```
 
 **Device Config**
 
 Getting credentials
Got credentials
{   'access_token': 'AZhaz161456274042178gLZmwkgFDcCdM',
    'expires_in': 864000,
    'refresh_token': 'AZhaz161456274042178gLZKYMECzui4K',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
Getting credentials
Got credentials
{   'access_token': 'AZhaz161456274042178gLZph8qxWn5IE',
    'expires_in': 864000,
    'refresh_token': 'AZhaz161456274042178gLZIikzmrBtQW',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'brightness': '1000',
                                                  'color_mode': 'white',
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1555070288771Se8MY/157298318737446dc35c0.png',
                                      'id': '0252057098f4abb7cbb5',
                                      'name': 'Lâmpada TV 1'},
                                  {   'data': {   'brightness': '1000',
                                                  'color_mode': 'white',
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1555070288771Se8MY/157298318737446dc35c0.png',
                                      'id': '0252057098f4abb7cc10',
                                      'name': 'Lâmpada TV 2'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'xk1AspmbB3bvXZtE',
                                      'name': 'Ligue todas as lâmpadas de uma '
                                              'vez'}],
                   'scenes': []}}
 **Additional Context**
 
Here the Homebridge log with brightness warning 

[3/8/2021, 8:30:11 PM] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 392 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/8/2021, 8:30:11 PM] [@milo526/homebridge-tuya-web] Error: 
    at Brightness.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at Brightness.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2118:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at BrightnessCharacteristic.updateValue (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/accessories/characteristics/brightness.ts:75:19)
    at /usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/accessories/characteristics/brightness.ts:34:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at listOnTimeout (internal/timers.js:523:9)
[3/8/2021, 8:30:11 PM] [TuyaWebPlatform] [Lâmpada TV 2] Characteristic.Hue - [GET] 0
[3/8/2021, 8:30:11 PM] [TuyaWebPlatform] [Lâmpada TV 2] Characteristic.Saturation - [GET] 0
[3/8/2021, 8:30:11 PM] [TuyaWebPlatform] [Lâmpada TV 1] - Unsetting debouncedDeviceStateRequestPromise
[3/8/2021, 8:30:11 PM] [TuyaWebPlatform] [Lâmpada TV 1] - Resolving resolveDeviceStateRequest from cache
[3/8/2021, 8:30:11 PM] [TuyaWebPlatform] [Lâmpada TV 1] Characteristic.On - [GET] true
[3/8/2021, 8:30:11 PM] [TuyaWebPlatform] [Lâmpada TV 1] Characteristic.Brightness - [GET] 1000
[3/8/2021, 8:30:11 PM] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 392 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[3/8/2021, 8:30:11 PM] [@milo526/homebridge-tuya-web] Error: 
    at Brightness.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at Brightness.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2118:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at BrightnessCharacteristic.updateValue (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/accessories/characteristics/brightness.ts:75:19)
    at /usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/accessories/characteristics/brightness.ts:34:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[3/8/2021, 8:30:11 PM] [TuyaWebPlatform] [Lâmpada TV 1] Characteristic.Hue - [GET] 0
[3/8/2021, 8:30:11 PM] [TuyaWebPlatform] [Lâmpada TV 1] Characteristic.Saturation - [GET] 0

**Comment by milo526** [comment] 2021-03-09 11:49
Duplicate of #220

**Closed** 2021-03-09 11:49 UTC
Labels: bug
