### ISSUE TITLE
Tuya device status in HomeKit

### ISSUE THREAD

**Issue by svobod3** [milo526/homebridge-tuya-web#208] opened 2021-02-23 11:59 UTC
**Describe the bug**

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment] 2021-02-23 12:01
Duplicate of #143 

(And you are missing most of the issue template)

**Closed by milo526** 2021-02-23 12:01 UTC
Labels: bug
