### ISSUE TITLE
Excessive Logging

### ISSUE THREAD

**Issue by Flip76** [milo526/homebridge-tuya-web#80] opened 2020-09-10 15:12 UTC
https://github.com/milo526/homebridge-tuya-web/issues/79

Sorry for opening a new issue but you already closed the other one. As I already mentioned in the bug description, debugging is not enabled (homebridge not startet with -D). Is there any hidden debug-parameter on plugin-level?

**Comment by milo526** [comment] 2020-09-10 15:13
Duplicate of #79 
There is no need to open a new issue for this. If you do not agree with me closing the issue respond to the closed issue (as you already did) and I will take another look at it.

**Closed by milo526** 2020-09-10 15:13 UTC
